apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - app-deployment.yaml
  - app-service.yaml
  - db-deployment.yaml
  - db-service.yaml
  - ../volumes/mysql-pvc.yaml
  - ../network/ingress.yaml
  - ../RBAC/serviceaccount.yaml
  - ../RBAC/role.yaml
  - ../RBAC/rolebinding.yaml