apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - app-deployment.yaml
  - app-service.yaml
  - db-deployment.yaml
  - db-service.yaml
  - storage/mysql-pvc.yaml
  - network/ingress.yaml
  - rbac/serviceaccount.yaml
  - rbac/role.yaml
  - rbac/rolebinding.yaml