apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: autocare360-rolebinding
  namespace: autocare360
subjects:
- kind: ServiceAccount
  name: autocare360-sa
  namespace: autocare360
roleRef:
  kind: Role
  name: autocare360-role
  apiGroup: rbac.authorization.k8s.io